CREATE DATABASE TripleCyber;
GO
USE TripleCyber
GO
CREATE SCHEMA Task;
GO
CREATE TABLE Task.Tasks
(
	Id INT NOT NULL IDENTITY(1,1),
	Task VARCHAR(250) NOT NULL,
	[Priority] SMALLINT NOT NULL DEFAULT(1),
	Solution VARCHAR(500) NULL,
	Created BIGINT NOT NULL,
	Solved BIGINT NULL,
    CONSTRAINT [PKTask] PRIMARY KEY(Id) 
)
GO
CREATE TABLE Task.Notes
(
	Id INT NOT NULL IDENTITY(1,1),
	TaskId INT NOT NULL,
	Note VARCHAR(200) NOT NULL,
	Created BIGINT NOT NULL,
	CONSTRAINT [PKNote] PRIMARY KEY(Id),
	CONSTRAINT FKNoteToTask FOREIGN KEY (TaskId)     
    REFERENCES Task.Tasks (Id)
)
GO